version: '3.9'

services:
  server:
    build:
      context: ..
      dockerfile: ./grpc/server/Dockerfile
    env_file:
      - ../.env
      - ./server/.env.example
    ports:
      - "50051:50051"
    depends_on:
      mongo:
        condition: service_healthy
  client:
    build:
      context: ..
      dockerfile: ./grpc/client/Dockerfile
    env_file:
      - ../.env
      - ./client/.env.example
    environment:
      GRPC_SERVER_URL: grpc://server:50051
    depends_on:
      server:
        condition: service_started
    tty: true
    stdin_open: true
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - grpc-mongo:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  grpc-mongo: